apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-frontend-deployment
  namespace: coderealm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-frontend
  template:
    metadata:
      labels:
        app: code-frontend
    spec:
      containers:
      - name: code-frontend
        image: lokeshkatari/coderealm-frontend:latest
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap:9092
        - name: GRPC_SERVER
          value: "code-exec-service.coderealm.svc.cluster.local"  
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
      - name: auth-envoy
        image : lokeshkatari/coderealm-auth-envoy-grpc:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"

